version: '3'

tasks:
  format: gofmt -w .
  lint: golangci-lint run --fix --timeout "10m"
  test: go test -tags fts5
  bench: go test -tags fts5 -bench=. -benchmem -run ^$
  default:
    cmds:
    - task: format
    - task: lint
    - task: test
